services:
  app:
    container_name: portfolio
    image: ghcr.io/yashdeeptandon/personal-portfolio:latest
    expose:
      - "3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
